FROM ubuntu:latest

ENV DEBIAN_FRONTEND=noninteractive
ENV GOOGLE_APPLICATION_CREDENTIALS=gcp.json
ENV GITHUB_TOKEN="Set with run"

# Package installation
RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    python3-venv \
    curl \
    git \
    software-properties-common
RUN add-apt-repository -y ppa:git-core/ppa && \
    apt-get install -y gh

# gcloud
RUN echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] http://packages.cloud.google.com/apt cloud-sdk main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
RUN curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
RUN apt-get update && apt-get install -y google-cloud-sdk

# Docker
RUN curl -fsSL https://get.docker.com -o get-docker.sh && \
    sh get-docker.sh

# Set up git
RUN git config --global user.name "lgaleana-LLM" && \
    git config --global user.email "lsgaleana+llm@gmail.com"
RUN mkdir -p /root/.ssh && chmod 700 /root/.ssh
COPY ssh/github /root/.ssh/github
RUN eval $(ssh-agent -s) && \
    ssh-add /root/.ssh/github && \
    ssh-keyscan -H github.com >> /root/.ssh/known_hosts

# Clean up
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /home

# Default command for the container
CMD ["bash"]
